spring:
  application:
    name: base-service
  datasource:
    url: jdbc:h2:mem:item
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  shutdown: graceful